const PerformersData = [
    {
        key: "performerData1",
        profileImg: "/images/profile/user-3.jpg",
        username: "Sunil Joshi",
        designation: "Web Designer",
        project: "Elite Admin",
        priority: "Low",
        color: "primary",
        bgcolor: "bg-primary text-white",
        budget: "3.9k",
    },
    {
        key: "performerData2",
        profileImg: "/images/profile/user-5.jpg",
        username: "John Deo",
        designation: "Web Developer",
        project: "Flexy Admin",
        priority: "Medium",
        color: "warning",
        bgcolor: "bg-warning text-white",
        budget: "24.5k",
    },
    {
        key: "performerData3",
        profileImg: "/images/profile/user-6.jpg",
        username: "Nirav Joshi",
        designation: "Web Manager",
        project: "Material Pro",
        priority: "High",
        color: "warning",
        budget: "12.8k",
    },
    {
        key: "performerData4",
        profileImg: "/images/profile/user-7.jpg",
        username: "Yuvraj Sheth",
        designation: "Project Manager",
        project: "Xtreme Admin",
        priority: "Low",
        color: "success",
        bgcolor: "bg-success text-white",
        budget: "4.8k",
    },
    {
        key: "performerData5",
        profileImg: "/images/profile/user-8.jpg",
        username: "Micheal Doe",
        designation: "Content Writer",
        project: "Helping Hands WP Theme",
        priority: "High",
        color: "error",
        bgcolor: "bg-error text-white",
        budget: "9.3k",
    },
];
export { PerformersData }