/**
 * Constants for the Beetween applicant-tracking / recruiting platform.
 *
 * Beetween (beetween.com) is a French recruitment software / ATS vendor (active
 * since 2007). Every customer tenant publishes a branded, public, unauthenticated
 * career site ("espace recrutement") that lists its open roles. There are two
 * shapes of public career surface in the wild:
 *
 *  1. The canonical, Beetween-hosted career portal served from the shared
 *     application host on a per-tenant path:
 *
 *       GET https://emploi.beetween.com/WeaselWeb/p/{tenant}
 *
 *     `WeaselWeb` is Beetween's servlet/application context (the same context
 *     that backs the documented application API host
 *     `https://api.beetween.com/WeaselWeb/...`). The portal renders the tenant's
 *     open roles, each linking to a public job-detail page.
 *
 *  2. A tenant vanity domain (custom career site) that surfaces the same roles,
 *     e.g. `https://recrutement.{tenant}.fr/offres-emploi/`, with each role at a
 *     `/poste/{publicId}-{slug}/` detail URL.
 *
 * Each open role is addressed by a Beetween "public id" — a sequence of
 * lower-case ASCII letters and digits, 10–20 characters long, auto-generated by
 * Beetween when an offer goes online (per Beetween's published API docs). It is
 * the stable per-offer identifier and is used here as the `atsId`. The role's
 * application reference also embeds it (e.g. `job-ref-{publicId}@emploi.beetween.com`).
 *
 * The adapter resolves a tenant from `companySlug` (the portal path segment, e.g.
 * `beetween`) or from a `companyUrl` (a vanity career domain). It then fetches
 * the tenant career page ONCE and harvests the embedded open-role references:
 * any inlined application state (a JSON blob the career SPA hydrates from) is
 * parsed first; otherwise the server-rendered `/poste/{publicId}-{slug}/` (and
 * `WeaselWeb`-style) offer links are scraped from the HTML. The list is sliced
 * client-side to honour `resultsWanted` and de-duplicated by public id.
 *
 * An unknown tenant (HTTP 404 / other 4xx), a network failure, or a malformed
 * payload degrades to an empty (graceful) result rather than throwing, so a
 * single bad tenant never breaks a batch run.
 *
 * Live-verification note (2026-06-03): Beetween's public career surface and the
 * `WeaselWeb` application context were confirmed live (e.g. the Beetween-owned
 * career site at `recrutement.beetween.fr` lists open roles at
 * `/poste/{publicId}-{slug}/`, with public ids such as `ulx92rl1lu` and
 * `koau35qzz6` matching the documented 10–20 char lower-alphanumeric format, and
 * the canonical portal lives at `emploi.beetween.com/WeaselWeb/p/`). Beetween's
 * documented API, however, is a PUSH connector (Beetween posts offers OUT to job
 * boards) — there is no documented public READ JSON endpoint that returns a
 * tenant's offer list, and the career SPA / api hosts were not reachable from
 * the verification sandbox. The wire-shape interfaces below are therefore
 * modelled DEFENSIVELY (both an inlined-JSON path and an HTML-scrape fallback),
 * and the verification metadata for this spec is recorded as `verified: false`.
 */

/** Shared public Beetween career-portal host. */
export const BEETWEEN_PORTAL_HOST = 'https://emploi.beetween.com';

/** Beetween application/servlet context shared by the portal and the API host. */
export const BEETWEEN_APP_CONTEXT = '/WeaselWeb';

/**
 * Canonical per-tenant career-portal path template. `{tenant}` is the public
 * portal slug (the trailing path segment of the Beetween-hosted career page).
 */
export const BEETWEEN_PORTAL_PATH_TEMPLATE = '/WeaselWeb/p/{tenant}';

/**
 * Matches a public job-detail link on a tenant career page, capturing the
 * Beetween public id (10–20 lower-case ASCII letters/digits) and the trailing
 * human-readable slug. Covers both vanity `/poste/{id}-{slug}/` links and the
 * portal's hash/route variants.
 */
export const BEETWEEN_OFFER_LINK_REGEX =
  /\/poste\/([a-z0-9]{8,24})-([a-z0-9-]+)\/?/gi;

/**
 * Matches a bare Beetween public id wherever it appears (e.g. embedded in an
 * application reference `job-ref-{publicId}@emploi.beetween.com` or an inlined
 * data blob). Per Beetween's API docs the id is 10–20 lower-case alphanumerics;
 * we relax the bounds slightly (8–24) to tolerate cross-tenant drift.
 */
export const BEETWEEN_PUBLIC_ID_REGEX = /\b([a-z0-9]{8,24})\b/;

/**
 * Matches an inlined JSON hydration blob the career SPA may embed in the page,
 * e.g. `window.__BEETWEEN_STATE__ = { ... };` or a `<script type="application/json">`
 * payload. Captured group 1 is the raw JSON text. Modelled defensively — the
 * adapter falls back to HTML link-scraping when no such blob is present.
 */
export const BEETWEEN_INLINE_STATE_REGEX =
  /(?:window\.__(?:BEETWEEN|INITIAL)_STATE__\s*=\s*|<script[^>]*type=["']application\/json["'][^>]*>)\s*({[\s\S]*?})\s*(?:;|<\/script>)/i;

/** Public job-detail URL template, anchored to the portal host. */
export const BEETWEEN_OFFER_URL_TEMPLATE = '/poste/{publicId}-{slug}/';

/**
 * Default internal results cap. Mirrors the sibling ATS adapters: when a caller
 * omits `resultsWanted` entirely we ingest up to 100 of the tenant's open roles.
 */
export const BEETWEEN_DEFAULT_RESULTS = 100;

/**
 * Bounded per-request timeout (seconds) used when the caller does not pass an
 * explicit `requestTimeout`. Beetween's portal host (`emploi.beetween.com`) can
 * intermittently hang on unknown/slow tenants; the shared HTTP client otherwise
 * defaults to 60s, which both blocks a batch run far too long and breaches the
 * 30s e2e test budget. Capping at 15s keeps the graceful-degradation path fast
 * (a single bad tenant degrades to an empty result well inside the budget)
 * while leaving ample headroom for a responsive tenant's normal sub-second
 * response. Callers can still override via `ScraperInputDto.requestTimeout`.
 */
export const BEETWEEN_DEFAULT_TIMEOUT_SECONDS = 15;

/** Default request headers. The career page expects a browser-like UA. */
export const BEETWEEN_HEADERS: Record<string, string> = {
  Accept: 'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8',
  'User-Agent':
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129 Safari/537.36',
  'Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7',
};
