-- Migration: 0000_init
-- Spec 004 / T07 — initial schema for `store-sqlite-drizzle` plugin.
--
-- This file is the SQL source-of-truth equivalent of `../schema.ts`. It is
-- written by hand (not generated by `drizzle-kit generate`) so the
-- migration file is reviewable and includes the SQLite-specific
-- `PRAGMA foreign_keys = ON` reminder. `drizzle-kit generate` may regenerate
-- this file in the future; the contract is that the SQL it produces MUST
-- be byte-identical to what's here, save for whitespace and the
-- `migration_journal.json` bookkeeping that drizzle-kit owns.
--
-- The application layer (`store-sqlite-drizzle.service.ts`) ALSO bootstraps
-- the schema via `INITIAL_SCHEMA_SQL` from `../schema.ts` so tests on
-- `:memory:` databases need no migration runner; this file remains the
-- authoritative on-disk migration for the production sqlite deployment.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS canonical_job (
  canonical_job_id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL,
  merged_at TEXT NOT NULL,
  fields_json TEXT NOT NULL DEFAULT '{}',
  sources_json TEXT NOT NULL DEFAULT '[]',
  company_lc TEXT NOT NULL,
  title_lc TEXT NOT NULL,
  location_lc TEXT NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_canonical_job_merged_at_id
  ON canonical_job (merged_at, canonical_job_id);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_canonical_job_company_lc
  ON canonical_job (company_lc);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_canonical_job_title_lc
  ON canonical_job (title_lc);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_canonical_job_location_lc
  ON canonical_job (location_lc);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS source_observation (
  canonical_job_id TEXT NOT NULL,
  site TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  url TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  raw_title TEXT,
  PRIMARY KEY (canonical_job_id, site, source_job_id),
  FOREIGN KEY (canonical_job_id)
    REFERENCES canonical_job (canonical_job_id)
    ON DELETE CASCADE
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS idx_source_observation_canonical_job_id
  ON source_observation (canonical_job_id);
